### PR TITLE
Support newer gilded-wordpress versions

### PR DESCRIPTION
**Pull request by staabm**
Depends on https://github.com/scottgonzalez/gilded-wordpress/pull/4

### CODE REVIEW

**Comment by scottgonzalez** [comment]
This module has a hard dependency on specific versions. This can't use ranges because the PHP portion is copied into this repo.

**Comment by staabm** [comment]
Is it not possible to distribute the php code within a npm package alongside the js?

**Comment by scottgonzalez** [comment]
`gilded-wordpress.php` is distributed as part of the `grunt-wordpress` package. However, it needs to be promoted to a first class citizen in this package as well, because `grunt-wordpress` users shouldn't be expected to dig into `node_modules` to find a required file to install in WordPress. So the problem is that allowing gilded-wordpress@1.0.4 to get installed as a dependency while `gilded-wordpress.php` is at v1.0.3 would cause the plugin to not work. The `gilded-wordpress` dependency must always be pinned to an exact version.

**Comment by staabm** [comment]
Couldnt you just use a `require` or `include` from your gilded-wordpress within your root of the one provided in node_modules?

**Comment by scottgonzalez** [comment]
No, this is a PHP file that needs to be manually copied by the user.

**Comment by staabm** [comment]
@scottgonzalez updated the bunlded gilded-wordpress and its dependency to 1.0.4

**Pull request closed without merging**
