### PR TITLE
Build: Upgrade gilded-wordpress

### PR DESCRIPTION
**Pull request by kborchers**

### CODE REVIEW

**Comment by scottgonzalez** [comment]
This requires manually copying over the PHP plugin as well.

**Comment by kborchers** [comment]
Ah, ok. Will push an update.

**Comment by scottgonzalez** [comment]
It's just the one file that needs to be copied over: `gilded-wordpress.php`

**Comment by kborchers** [comment]
Any chance we could get this merged soon so we can get the sites deploying properly again?

**Comment by scottgonzalez** [comment]
Sorry, I was waiting for a comment to let me know the PR was updated. By the time you wrote another comment I was on vacation.

This has been released in v2.1.2.

**Pull request closed without merging**
